### ISSUE TITLE
Wdiget Update

### ISSUE THREAD

**Issue by Rapter1990** [rajtheinnovator/FindL#1]
Hi,
There is no time to make a communication with you.
I want to ask you about updating widget issue.
Have you ever checked it out?
Thank you.

**Comment by rajtheinnovator** [comment]
@Rapter1990 to discuss things better, I'd suggest connecting with me on LinkedIn, if you're open to it. Here's my profile: https://www.linkedin.com/in/iamabhishekraj/

**Comment by Rapter1990** [comment]
As there is no result in message list after writitng your profile name in textbox, I couldn't send any message to you.

**Comment by rajtheinnovator** [comment]
Widget instantaneous update now works
